services:
  roop:
    build:
      context: .
      dockerfile: Dockerfile-python
    volumes:
      - .:/app
      - .insightface:/.insightface
    user: 1000:1000
    deploy:
     resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
