FROM python:3.11

RUN apt-get update && apt-get install -y \
	ffmpeg

ADD requirements.txt .
RUN pip install -r requirements.txt

RUN mkdir -p /.config/matplotlib /.cache/matplotlib /.opennsfw2 && \
	chown -R 1000 /.config /.cache /.opennsfw2

CMD /bin/bash

WORKDIR /app
USER 1000
